#!/usr/bin/perl
use strict;

# This program takes as input a bed file generated by bedtools bamtobed program and counts the number of insertion sites as the most 3'end of the mapped read 1.

my $SCORE_CUTOFF = 40;
my %isdb;

while(<>){
    chomp; 
    my @x = split /\t/;
    my $is_id;
    my ($chr, $end5, $end3, $score, $strand) = ($x[0],$x[1],$x[2],$x[4],$x[5]); 
    if ($strand eq "+"){
        my $new5 = $end3 - 34;
        my $new3 = $end3 + 30;
        $is_id = "$chr:$new5-$new3-$end3:$strand";
    } else {
        my $new5 = $end5 - 30;
        my $new3 = $end5 + 34;
        $is_id = "$chr:$new5-$new3-$end5:$strand";
    }

    if($score >= $SCORE_CUTOFF){
        $isdb{$is_id}++
    }
};

# Print header
print "#Chromosome\tflank_5\tflank_3\tcounts\tIS_coord\tread_strand\n";

foreach my $is_id (keys %isdb){
    my ($ch, $co5, $co3, $hit, $strand) = ($1, $2, $3, $4, $5) if $is_id =~ m/^(\S+):(\d+)-(\d+)-(\d+):(\S+)$/;
    my $count = $isdb{$is_id}; 
    print "$ch\t$co5\t$co3\t$count\t$hit\t$strand\n"  
}



